# -----------------------
# Basic config
# -----------------------
# set -g default-shell /usr/bin/zsh
set -g default-terminal screen-256color
set -sg escape-time 0
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g prefix C-a
setw -g mouse on

# -----------------------
# Key Bindings
# -----------------------
unbind C-b
bind C-a send-prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# -----------------------
# Status Bar
# -----------------------
set -g status-position top
set -g status-interval 1
set -g status-justify absolute-centre
set -g status-left-length 100
set -g status-right-length 120
set -g focus-events on

# -----------------------
# Bell Config (for Claude Code notifications)
# -----------------------
# activity
set -g monitor-activity on
set -g visual-activity both
set -g activity-action other
set -g window-status-activity-style 'reverse'

# bell
set -g monitor-bell on
set -g visual-bell both
set -g bell-action other
set -g window-status-bell-style 'reverse'

set -g monitor-silence 180
set -g silence-action other
set -g visual-silence on

# -----------------------
# Pane Style
# -----------------------
set -sa terminal-overrides ',xterm-256color:RGB'

# -----------------------
# Copy Mode
# -----------------------
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel
bind -T copy-mode C-u send-keys -X page-up
bind -T copy-mode C-d send-keys -X page-down

# -----------------------
# Catppuccin Theme
# -----------------------
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_modules_right "directory session date_time"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"

# -----------------------
# Plugin Config
# -----------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'thewtex/tmux-mem-cpu-load'
set -g @plugin 'catppuccin/tmux'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
