---
- name: Add SSH key from GitHub users to the specified user
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items: "{{ github_users }}"