name: chezmoi check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  chezmoi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotfiles
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io/get)" -- init --apply -S .
